version: '3.3'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/test/portainer/data:/data
    environment:
      VIRTUAL_PORT: 9000

#volumes:
#  portainer_data: